# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
default: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  username: postgres
  password: "Guidance"
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_backend_development

test:
  <<: *default
  database: hello_rails_backend_test

production:
  <<: *default
  database: "Hello-rails-backend_production"
  username: "Hello-rails-backend"
  password: <%= ENV['HELLO_RAILS_BACKEND_DATABASE_PASSWORD'] %>
